### ISSUE TITLE
Uncaught TypeError: _this.notificationEl.querySelector is not a function

### ISSUE THREAD

**Issue by YoungJuleke** [spark/particle-dev-complete#3]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.18.0-dev-071ee3a x64
**Electron**: 1.3.15
**OS**: Ubuntu 16.04.2
**Thrown From**: [particle-dev-complete](https://github.com/spark/particle-dev-complete) package 1.0.1

### Stack Trace

Uncaught TypeError: _this.notificationEl.querySelector is not a function

```
At /home/jules/.atom/packages/particle-dev-complete/node_modules/atom-package-deps/lib/view.js:22

TypeError: _this.notificationEl.querySelector is not a function
    at /packages/particle-dev-complete/node_modules/atom-package-deps/lib/view.js:22:58
```

### Commands

```
```

### Non-Core Packages

```
particle-dev-complete 1.0.1 
```

**Comment by suda** [comment]
It's possible we need to update `atom-package-deps` dependency.

**Comment by mulad** [comment]
What packages are missing? I tried adding the linter and linter-ui-default packages as suggested at the link below, but that didn't help me:
https://github.com/hebaishi/linter-gcc/issues/126

**Comment by erlendbirketvedt** [comment]
Any workaround? I would love to use this.

**Comment by awkwardengineer** [comment]
I'm getting the local IDE set up and had the same issue

-edit: work around was to install each item in the package manually

**Comment by nfrumkin** [comment]
I got an error which is identical to the one above. I tried installing the dependencies separately and got the following error:

apm install console-panel
Installing console-panel to /home/natalia/.atom/packages ✓

apm install tool-bar
Installing tool-bar to /home/natalia/.atom/packages ✓

apm install particle-dev
Installing particle-dev to /home/natalia/.atom/packages ✗

> serialport@4.0.1 install /tmp/apm-install-dir-117520-21346-4wjxkf.ub7tgo80k9/node_modules/particle-dev/node_modules/serialport
> node-pre-gyp install --fallback-to-build

Failed to execute '/usr/share/atom/resources/app/apm/bin/node /usr/share/atom/resources/app/apm/bin/../node_modules/.bin/node-gyp configure --fallback-to-build --module=/tmp/apm-install-dir-117520-21346-4wjxkf.ub7tgo80k9/node_modules/particle-dev/node_modules/serialport/build/Release/serialport.node --module_name=serialport --module_path=/tmp/apm-install-dir-117520-21346-4wjxkf.ub7tgo80k9/node_modules/particle-dev/node_modules/serialport/build/Release' (1)
/tmp/apm-install-dir-117520-21346-4wjxkf.ub7tgo80k9
└── (empty)


npm WARN deprecated spark@0.5.10: Use particle-api-js instead
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN excluding symbolic link test/server/static/ie8-polyfill.js -> ../../../ie8-polyfill.js
npm WARN excluding symbolic link test/server/static/ie8-polyfill.js -> ../../../ie8-polyfill.js
node-pre-gyp ERR! Tried to download(404): https://github.com/suda/node-serialport/releases/download/4.0.1/serialport-v4.0.1-electron-v1.3-linux-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for serialport@4.0.1 and electron@1.3.15 (electron-v1.3 ABI) (falling back to source compile with node-gyp) 
gyp ERR! configure error 
gyp ERR! stack Error: Python executable "/usr/share/atom/resources/app/apm/bin/python-interceptor.sh" is v3.5.2, which is not supported by gyp.
gyp ERR! stack You can pass the --python switch to point to Python >= v2.5.0 & < 3.0.0.
gyp ERR! stack     at failPythonVersion (/usr/share/atom/resources/app/apm/node_modules/node-gyp/lib/configure.js:454:14)
gyp ERR! stack     at /usr/share/atom/resources/app/apm/node_modules/node-gyp/lib/configure.js:443:9
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:197:7)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at maybeClose (internal/child_process.js:877:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
gyp ERR! System Linux 4.4.0-79-generic
gyp ERR! command "/usr/share/atom/resources/app/apm/bin/node" "/usr/share/atom/resources/app/apm/node_modules/.bin/node-gyp" "configure" "--fallback-to-build" "--module=/tmp/apm-install-dir-117520-21346-4wjxkf.ub7tgo80k9/node_modules/particle-dev/node_modules/serialport/build/Release/serialport.node" "--module_name=serialport" "--module_path=/tmp/apm-install-dir-117520-21346-4wjxkf.ub7tgo80k9/node_modules/particle-dev/node_modules/serialport/build/Release"
gyp ERR! cwd /tmp/apm-install-dir-117520-21346-4wjxkf.ub7tgo80k9/node_modules/particle-dev/node_modules/serialport
gyp ERR! node -v v6.9.5
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/share/atom/resources/app/apm/bin/node /usr/share/atom/resources/app/apm/bin/../node_modules/.bin/node-gyp configure --fallback-to-build --module=/tmp/apm-install-dir-117520-21346-4wjxkf.ub7tgo80k9/node_modules/particle-dev/node_modules/serialport/build/Release/serialport.node --module_name=serialport --module_path=/tmp/apm-install-dir-117520-21346-4wjxkf.ub7tgo80k9/node_modules/particle-dev/node_modules/serialport/build/Release' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/tmp/apm-install-dir-117520-21346-4wjxkf.ub7tgo80k9/node_modules/particle-dev/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:106:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:877:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
node-pre-gyp ERR! System Linux 4.4.0-79-generic
node-pre-gyp ERR! command "/usr/share/atom/resources/app/apm/bin/node" "/tmp/apm-install-dir-117520-21346-4wjxkf.ub7tgo80k9/node_modules/particle-dev/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /tmp/apm-install-dir-117520-21346-4wjxkf.ub7tgo80k9/node_modules/particle-dev/node_modules/serialport
node-pre-gyp ERR! node -v v6.9.5
node-pre-gyp ERR! node-pre-gyp -v v0.6.36
node-pre-gyp ERR! not ok 
npm WARN enoent ENOENT: no such file or directory, open '/tmp/apm-install-dir-117520-21346-4wjxkf.ub7tgo80k9/package.json'
npm WARN apm-install-dir-117520-21346-4wjxkf.ub7tgo80k9 No description
npm WARN apm-install-dir-117520-21346-4wjxkf.ub7tgo80k9 No repository field.
npm WARN apm-install-dir-117520-21346-4wjxkf.ub7tgo80k9 No README data
npm WARN apm-install-dir-117520-21346-4wjxkf.ub7tgo80k9 No license field.
npm ERR! Linux 4.4.0-79-generic
npm ERR! argv "/usr/share/atom/resources/app/apm/bin/node" "/usr/share/atom/resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/home/natalia/.atom/.apm/.apmrc" "--userconfig" "/home/natalia/.atom/.apmrc" "install" "/tmp/d-117520-21346-s2jynx.zzifab57b9/package.tgz" "--runtime=electron" "--target=1.3.15" "--arch=x64" "--global-style"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! serialport@4.0.1 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the serialport@4.0.1 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the serialport package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs serialport
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls serialport
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /tmp/apm-install-dir-117520-21346-4wjxkf.ub7tgo80k9/npm-debug.log
npm ERR! code 1

**Comment by awkwardengineer** [comment]
I was able to work around by adding all the individual packages one at a time

**Comment by rylwin** [comment]
I was also able to resolve by adding the individual packages. I may have gone a bit overboard, but here are all the packages I installed to get past the error:
```
apm install linter
apm install linter-ui-default
apm install particle-dev-cloud-functions
apm install particle-dev-cloud-variables
apm install particle-dev-profiles
apm install particle-dev-libraries
# NOTE: I still saw the error here. On boot atom suggested 
# installing missing deps: particle-dev, tool-bar. Then it worked.
apm install particle-dev
apm install tool-bar
```

**Comment by suda** [comment]
This error is caused by an outdated version of `atom-package-deps` package. We've updated it in all our packages so it should go away. There are still 3rd party packages that might have this bug. I created a [PR for `linter-gcc`(https://github.com/hebaishi/linter-gcc/pull/137) to fix it at least.
